# -*- coding: utf-8 -*-
"""CC1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bu3inTo4V_5xicEiAmQBSAvy45Sbnj5A
"""

# -------------------------------
# 1. Data Types Example
# -------------------------------

math = 40
pi = 3.14
name = 'Rd'

print(type(math))
print(type(pi))
print(type(name))


# -------------------------------
# 2. Basic Addition
# -------------------------------

print(2 + 2)        # Integer addition
print("2" + "2")    # String concatenation


# -------------------------------
# 3. Input and Type Casting
# -------------------------------

val = int(input("Enter first number: "))
val2 = int(input("Enter second number: "))
print(val + val2)


# -------------------------------
# 4. Integer Conversion
# -------------------------------

print(int(3.14))
print(int(True))
print(int(False))
print(int("4"))


# -------------------------------
# 5. Float Conversion
# -------------------------------

print(float(3.14))
print(float(True))
print(float(False))
print(float("4.22"))


# -------------------------------
# 6. Complex Conversion
# -------------------------------

print(complex(2))
print(complex(True))
print(complex(False))


# -------------------------------
# 7. Boolean Conversion
# -------------------------------

print(bool(True))
print(bool(35))
print(bool(0))


# -------------------------------
# 8. Simple Interest Program
# SI = (P × R × T) / 100
# -------------------------------

p = 10000
roi = 10
time = 1

SI = p * roi * time / 100
print("SI =", SI)


# -------------------------------
# 9. Celsius to Fahrenheit
# F = (9/5 × C) + 32
# -------------------------------

T_c = 32
T_F = (9 / 5 * T_c) + 32

print(T_F)


# -------------------------------
# 10. Swap Using Temporary Variable
# -------------------------------

v1 = 21
v2 = 12

temp = v1
v1 = v2
v2 = temp

print(v1)
print(v2)


# -------------------------------
# 11. Swap Without Temporary Variable
# -------------------------------

a = 12
b = 21

a = a + b
b = a - b
a = a - b

print("a =", a)
print("b =", b)


# -------------------------------
# 12. Feet to Inches and CM
# -------------------------------

h_feet = 12
h_inch = h_feet * 12
h_cm = h_inch * 2.54

print(h_inch)
print(h_cm)


# -------------------------------
# 13. Reverse a 3-digit Number
# -------------------------------

num = 123

a = num % 10
num = num // 10

b = num % 10
num = num // 10

c = num % 10

rev = a * 100 + b * 10 + c
print(rev)