# -*- coding: utf-8 -*-
"""CC_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HXjd9AzGNdrpFn1GegmI5ZQTzZ8g8s7Z
"""

#nested if
n1=int(input("enter"))
n2=int(input("enter"))
n3=int(input("enter"))

if n1>n2 and n1>n3:
    print("max number =", n1)
elif n2>n1 and n2>n3:
    print("max number =", n2)
else:
    print("max number =", n3)

#elseif ladder
#wap to accept percentage and if peercentage greater taan 90 then assign grade a  , b, c d
per=int(input("enter"))
if per>90:
    print("Grade A")
elif per>80 and per<90:
    print("Grade B")
elif per>70 and per<80:
    print("Grade C")
else:
    print("failed")

#dictionay datatype
mydict={
"name":"swanand",
"professional":"student",
"rollno":"1001001"

}
print(mydict)
print(type(mydict))

#dictionary duplicate values
mydict1={
101:"rd",
102:"mahi",
103:"virat",
104:"Mahi",
104:"Mahi",
105:"panda"

}
print(mydict1)

print(mydict1[102])

for x in mydict1:
    print(x)

for x in mydict1.values():
    print(x)

for x,y in mydict1.items():
    print(x,y)

mydict1["mobileno"]=54545443545
print(mydict1)
mydict1.pop(105)
print(mydict1)

#string slicing
name = "swanandD"
# print(name[0])
# print(name[1])
# print(name[2])
# print(name[3])
# print(name[4])
# print(name[5])
for i in range (7):
    print(name[i])
name[-1]
name[0:5]
name[1:7]

s= "youtube is the best website to learn anything"
print(s.find("youtube"))
print(s.find("learn"))
print(s.find("best"))

s="swanand","drstone","cd"
m="|".join(s)
print(s)

g="python3 is a high level programming language"
print(g.lower())
print(g.upper())
print(g.swapcase())
print(g.title())
print(g.capitalize())

print("subject marks")
phy =90
chem=76
math=87
print("phy={} chem={} math={}".format(phy,chem,math))
print("phy={0} chem={1} math={2}".format(phy,chem,math))
print("phy={x} chem={y} math={z}".format(x=phy,y=chem,z=math))
total = phy + chem + math
print("total marks",f"{total}")
print("rollno","7".zfill(4))

print('swanand100'.isalnum())
print('swanand100'.isalpha())
print('swanand100'.islower())
print('swanand100'.isupper())
print('swanand100'.isdigit())
print(''.istitle())
print(''.isspace())
print("hello".startswith("he"))

#BODMAS
a=50
b=30
c=20
d=10
print((a+b)*c/d)
print((a-b)*(c/d))
print(a+(b*c)/d)

x=['A','B','C']
y=['A','B','C']
z=[1,2,3,4]
print(x==y)
print(x==z)
print(x !=z)

name2="swanandandbravo"
count_const=0
count_vowel=0
for i in name2 :
    if(i=='a' or i=='e' or i=='i' or i=='o' or i=='u'):
        count_vowel=count_vowel+1
    else:
        count_const=count_const+1
print(count_vowel)
print(count_const)

data=['a','e','i','o','u']
v_count=0
c_count=0
for i in name2:
    if i in data:
        v_count+=1
    else:
        c_count+=1
print(v_count)
print(c_count)

name4 = []
for i in range(len(name2)):
    found = False
    for j in range(len(name4)):
        if name2[i] == name4[j]:
            found = True
    if not found:
        name4.append(name2[i])

print(name4)