# -*- coding: utf-8 -*-
"""CC_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bu3inTo4V_5xicEiAmQBSAvy45Sbnj5A
"""

# Break example
for i in range(1, 5):
    if i == 3:
        break
    print(i)


# Continue example
for i in range(1, 5):
    if i == 3:
        continue
    print(i)


# Zip example
for i, j in zip(range(1, 6), range(5, 0, -1)):
    if i == 3 and j == 3:
        continue
    print(i, j)


# While loop
i = 1
while i <= 5:
    print(i)
    i = i + 1


# Username password check
username = ''
password = ''

while username != "admin" and password != "hello":
    username = input("Enter username: ")
    password = input("Enter password: ")


# Sum of first n numbers
n = int(input("Enter number: "))
sum = 0
i = 1

while i <= n:
    sum = sum + i
    i = i + 1

print("The sum of first", n, "numbers is:", sum)


# Remove duplicate characters from string
name = "prashant"
result = ""

for i in name:
    if i not in result:
        result += i

print(name)
print(result)


# Reverse string using loop
name = "Prashant"
rev = ""

for char in name:
    rev = char + rev

print(rev)


# Cart example
mycart = [10, 20, 200, 300, 800, 60, 700]

for i in mycart:
    if i > 400:
        print("This my purchased cart item")
        continue
    print(i)


# Palindrome check
n = input("Enter: ")

if n == n[::-1]:
    print("Palindrome string")
else:
    print("Not a palindrome string")


# Anagram check
w1 = input("Enter first word: ")
w2 = input("Enter second word: ")

if sorted(w1) == sorted(w2):
    print("These are anagrams")
else:
    print("Not anagrams")


# Add key to dictionary
dictionary = {"name": "Alice"}
key = "age"
value = 30

dictionary[key] = value
print(dictionary)


# Remove key from dictionary
dictionary = {"name": "Alice", "age": 30}
del dictionary["age"]
print(dictionary)


# Nested loop example
for i in range(1, 4):
    for j in range(1, 4):
        print(i, end=" ")
    print()


# Alphabet pattern
n = int(input("Enter the number of rows: "))
for i in range(1, n + 1):
    for j in range(1, n + 1):
        print(chr(64 + i), end=" ")
    print()


# Reverse number pattern
n = int(input("Enter the number of rows: "))
for i in range(1, n + 1):
    for j in range(1, n + 1):
        print(n + 1 - i, end=" ")
    print()


# Star pattern
n = int(input("Enter the number of rows: "))
for i in range(1, n + 1):
    for j in range(1, n + 2 - i):
        print("*", end=" ")
    print()