# -*- coding: utf-8 -*-
"""CC_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bu3inTo4V_5xicEiAmQBSAvy45Sbnj5A
"""

# -------------------------------
# Function to Add Two Numbers
# -------------------------------

def add():
    n1 = int(input("Enter first number: "))
    n2 = int(input("Enter second number: "))
    print("Add =", n1 + n2)

add()


# -------------------------------
# Function Returning Multiple Values
# -------------------------------

def add1():
    n1 = int(input("Enter first number: "))
    n2 = int(input("Enter second number: "))

    sum = n1 + n2
    sub = n1 - n2
    mul = n1 * n2
    div = n1 / n2

    return sum, sub, mul, div


result = add1()
print(result)


# -------------------------------
# Function with Arguments
# -------------------------------

def personalinfo(fname, lname):
    print("fname =", fname)
    print("lname =", lname)


namef = "rudram"
namel = "dindorkar"

personalinfo(namef, namel)


# -------------------------------
# Default Argument Example
# -------------------------------

def city_name(city="mumbai"):
    print(city)


city_name("nagpur")
city_name()


# -------------------------------
# Variable Length Arguments
# -------------------------------

def student_names(*name):
    print(name)


student_names("rudram", "rohit", "virat", "mahi", "ishan", "panda")


# -------------------------------
# Linear Search Function
# -------------------------------

mylist = [1, 4, 5, 2, 7, 9]

def search(target, mylist):
    for i in mylist:
        if i == target:
            print("Found target:", i)
            return i
    return -1


tar = int(input("Enter number to search: "))
ans = search(tar, mylist)
print(ans)