# -*- coding: utf-8 -*-
"""CC_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eEHZo6OjdUvNfU-c2x7Yrc7cqXXINf0G
"""

fruit_list1 = ['Apple' , 'Berry' , 'Cherry' , 'papaya']
fruit_list2 = fruit_list1 #both list  1 and 2 will have same address
fruit_list3 = fruit_list1[:]
fruit_list2[0] ='Guava'
fruit_list3[1] ='Kiwi'


sum=0
for ls in (fruit_list1 , fruit_list2 , fruit_list3):
    if ls[0] == 'Guava':
        sum +=1

    if ls[1] == 'Kiwi':
        sum +=20
print(sum)

def f(i , values = []):
      values.append(i)
      print(values)
      return values
f(1)
f(2)
f(3)

def fun(value , values):
  var=1
  values[0] = 44
t=3
v=[1,2,3]
fun(t,v)
print(t,v[0])

dict = {'c':97 , 'a':96 , 'b':98}
for _ in sorted(dict):
  print(dict[_])

fruit={}
def addone(index):
  if index in fruit:
    fruit[index] +=1
  else:
    fruit[index] =1
addone('Apple')
addone('Banana')
addone('apple')
addone('Apple')
print(len(fruit))

#given an array return an array where each element is the product of all the element in the array except itself
def product_(nums):
    n = len(nums)
    res = [1] * n

    left = 1
    for i in range(n):
        res[i] = left
        left *= nums[i]

    right = 1
    for i in range(n - 1, -1, -1):
        res[i] *= right
        right *= nums[i]

    return res
product_([1,2,3,4])